"use client";
import { useEffect, useState } from 'react';
import { Download, Upload, RotateCcw, Save, ChevronDown, Plus, Trash2 } from 'lucide-react';
import { cloneDefault } from '../content';
import '../admin.css';

const STORAGE='nestpro-cms-v1';
const clone=x=>JSON.parse(JSON.stringify(x));
function Input({label,value,onChange,textarea=false}){return <label className="cms-field"><span>{label}</span>{textarea?<textarea value={value??''} onChange={e=>onChange(e.target.value)}/>:<input value={value??''} onChange={e=>onChange(e.target.value)}/>}</label>}
function Section({title,open,onToggle,children}){return <section className="cms-section"><button className="cms-section-head" onClick={onToggle}><strong>{title}</strong><ChevronDown className={open?'rotate':''}/></button>{open&&<div className="cms-section-body">{children}</div>}</section>}
export default function Admin(){
 const [c,setC]=useState(cloneDefault()); const [msg,setMsg]=useState(''); const [open,setOpen]=useState({general:true,hero:true,features:true,workflow:true,pricing:true,faq:true,theme:true});
 useEffect(()=>{try{const raw=localStorage.getItem(STORAGE);if(raw)setC(JSON.parse(raw));}catch{}},[]);
 const update=(path,val)=>setC(prev=>{const next=clone(prev);let ref=next;for(let i=0;i<path.length-1;i++)ref=ref[path[i]];ref[path.at(-1)]=val;return next});
 const save=()=>{localStorage.setItem(STORAGE,JSON.stringify(c));setMsg('Saved');setTimeout(()=>setMsg(''),1800)};
 const reset=()=>{if(!confirm('Reset all CMS content?'))return;const d=cloneDefault();setC(d);localStorage.setItem(STORAGE,JSON.stringify(d));setMsg('Reset')};
 const exportJson=()=>{const blob=new Blob([JSON.stringify(c,null,2)],{type:'application/json'});const u=URL.createObjectURL(blob);const a=document.createElement('a');a.href=u;a.download='nest-pro-content.json';a.click();URL.revokeObjectURL(u)};
 const importJson=e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const data=JSON.parse(r.result);setC(data);localStorage.setItem(STORAGE,JSON.stringify(data));setMsg('Imported')}catch{setMsg('Invalid JSON')}};r.readAsText(f)};
 return <div className="cms"><aside className="cms-sidebar"><div className="cms-brand">NEST-PRO <span>CMS</span></div><p>Edit the website without touching the JSX.</p><a href="/" target="_blank" rel="noreferrer">Open website ↗</a><div className="cms-actions"><button onClick={save}><Save size={16}/> Save changes</button><button onClick={reset}><RotateCcw size={16}/> Reset</button><button onClick={exportJson}><Download size={16}/> Export JSON</button><label className="cms-upload"><Upload size={16}/> Import JSON<input type="file" accept="application/json" onChange={importJson}/></label></div><div className="cms-tip">Content is saved in this browser with localStorage. Export JSON to back up or move it. For multi-user cloud editing, connect this schema to a database later.</div></aside>
 <main className="cms-main"><header className="cms-top"><div><p>ADMIN CMS</p><h1>Edit Nest-Pro visually.</h1></div>{msg&&<div className="cms-toast">{msg}</div>}</header>
 <Section title="General & Navigation" open={open.general} onToggle={()=>setOpen({...open,general:!open.general})}><div className="cms-grid two"><Input label="Brand" value={c.site.brand} onChange={v=>update(['site','brand'],v)}/><Input label="Brand tag" value={c.site.brandTag} onChange={v=>update(['site','brandTag'],v)}/><Input label="Get Nest-Pro button" value={c.site.navBuy} onChange={v=>update(['site','navBuy'],v)}/><Input label="Page title" value={c.site.pageTitle} onChange={v=>update(['site','pageTitle'],v)}/></div><div className="cms-grid three">{c.site.navLinks.map((x,i)=><Input key={i} label={`Nav ${i+1}`} value={x} onChange={v=>{const a=[...c.site.navLinks];a[i]=v;update(['site','navLinks'],a)}}/>)}</div></Section>
 <Section title="Hero" open={open.hero} onToggle={()=>setOpen({...open,hero:!open.hero})}><div className="cms-grid two"><Input label="Eyebrow" value={c.hero.eyebrow} onChange={v=>update(['hero','eyebrow'],v)}/><Input label="Vertical note" value={c.hero.note} onChange={v=>update(['hero','note'],v)}/><Input label="Title line 1" value={c.hero.titleLine1} onChange={v=>update(['hero','titleLine1'],v)}/><Input label="Title line 2" value={c.hero.titleLine2} onChange={v=>update(['hero','titleLine2'],v)}/></div><Input label="Description" textarea value={c.hero.text} onChange={v=>update(['hero','text'],v)}/><div className="cms-grid two"><Input label="Primary CTA" value={c.hero.primaryCta} onChange={v=>update(['hero','primaryCta'],v)}/><Input label="Secondary CTA" value={c.hero.secondaryCta} onChange={v=>update(['hero','secondaryCta'],v)}/></div></Section>
 <Section title="Features" open={open.features} onToggle={()=>setOpen({...open,features:!open.features})}>{c.features.map((f,i)=><div className="cms-repeat" key={i}><div className="cms-repeat-head"><b>Feature {i+1}</b>{c.features.length>1&&<button onClick={()=>update(['features'],c.features.filter((_,idx)=>idx!==i))}><Trash2 size={15}/></button>}</div><div className="cms-grid two"><Input label="Number" value={f.n} onChange={v=>{const a=c.features.map(x=>({...x}));a[i].n=v;update(['features'],a)}}/><Input label="Icon" value={f.icon} onChange={v=>{const a=c.features.map(x=>({...x}));a[i].icon=v;update(['features'],a)}}/><Input label="Title" value={f.title} onChange={v=>{const a=c.features.map(x=>({...x}));a[i].title=v;update(['features'],a)}}/><Input label="Text" textarea value={f.text} onChange={v=>{const a=c.features.map(x=>({...x}));a[i].text=v;update(['features'],a)}}/></div></div>)}<button className="cms-add" onClick={()=>update(['features'],[...c.features,{n:String(c.features.length+1).padStart(2,'0'),icon:'sparkles',title:'New feature',text:'Describe this feature.'}])}><Plus size={15}/> Add feature</button></Section>
 <Section title="Workflow" open={open.workflow} onToggle={()=>setOpen({...open,workflow:!open.workflow})}><div className="cms-grid two"><Input label="Eyebrow" value={c.workflow.eyebrow} onChange={v=>update(['workflow','eyebrow'],v)}/><Input label="Title" value={c.workflow.title} onChange={v=>update(['workflow','title'],v)}/></div><Input label="Description" textarea value={c.workflow.text} onChange={v=>update(['workflow','text'],v)}/>{c.workflow.steps.map((s,i)=><div className="cms-step" key={i}><Input label={`Step ${i+1}`} value={s[0]} onChange={v=>{const a=c.workflow.steps.map(x=>[...x]);a[i][0]=v;update(['workflow','steps'],a)}}/><Input label="Title" value={s[1]} onChange={v=>{const a=c.workflow.steps.map(x=>[...x]);a[i][1]=v;update(['workflow','steps'],a)}}/><Input label="Description" value={s[2]} onChange={v=>{const a=c.workflow.steps.map(x=>[...x]);a[i][2]=v;update(['workflow','steps'],a)}}/></div>)}</Section>
 <Section title="Pricing" open={open.pricing} onToggle={()=>setOpen({...open,pricing:!open.pricing})}><div className="cms-grid two"><Input label="Eyebrow" value={c.pricing.eyebrow} onChange={v=>update(['pricing','eyebrow'],v)}/><Input label="Title" value={c.pricing.title} onChange={v=>update(['pricing','title'],v)}/></div><Input label="Intro text" textarea value={c.pricing.text} onChange={v=>update(['pricing','text'],v)}/>{c.pricing.cards.map((p,i)=><div className="cms-step" key={i}><Input label="Plan" value={p[0]} onChange={v=>{const a=c.pricing.cards.map(x=>[...x]);a[i][0]=v;update(['pricing','cards'],a)}}/><Input label="Price" value={p[1]} onChange={v=>{const a=c.pricing.cards.map(x=>[...x]);a[i][1]=v;update(['pricing','cards'],a)}}/><Input label="Period" value={p[2]} onChange={v=>{const a=c.pricing.cards.map(x=>[...x]);a[i][2]=v;update(['pricing','cards'],a)}}/><Input label="Description" value={p[3]} onChange={v=>{const a=c.pricing.cards.map(x=>[...x]);a[i][3]=v;update(['pricing','cards'],a)}}/></div>)}</Section>
 <Section title="FAQ" open={open.faq} onToggle={()=>setOpen({...open,faq:!open.faq})}><div className="cms-grid two"><Input label="Eyebrow" value={c.faq.eyebrow} onChange={v=>update(['faq','eyebrow'],v)}/><Input label="Title" value={c.faq.title} onChange={v=>update(['faq','title'],v)}/></div>{c.faq.items.map((item,i)=><div className="cms-step" key={i}><Input label="Question" value={item[0]} onChange={v=>{const a=c.faq.items.map(x=>[...x]);a[i][0]=v;update(['faq','items'],a)}}/><Input label="Answer" textarea value={item[1]} onChange={v=>{const a=c.faq.items.map(x=>[...x]);a[i][1]=v;update(['faq','items'],a)}}/></div>)}</Section>
 <Section title="Dark Theme / Interface" open={open.theme} onToggle={()=>setOpen({...open,theme:!open.theme})}><div className="cms-grid three">{Object.entries(c.theme).filter(([k])=>k!=='radius').map(([k,v])=><Input key={k} label={k} value={v} onChange={val=>update(['theme',k],val)}/>)}</div><Input label="Corner radius (px)" value={c.theme.radius} onChange={v=>update(['theme','radius'],v)}/><div className="cms-preview"><div style={{background:c.theme.pageBg,color:c.theme.text}}>Page background</div><div style={{background:c.theme.surface,color:c.theme.text}}>Surface</div><div style={{background:c.theme.accent,color:c.theme.accentText}}>Accent</div></div></Section>
 </main></div>
}
