"use client";
import { useEffect, useMemo, useState } from "react";
import { ArrowRight, Check, Layers3, Move, RotateCw, ScanLine, Sparkles, Zap } from "lucide-react";
import { defaultContent } from "./content";

const ICONS={scan:ScanLine,layers:Layers3,rotate:RotateCw,move:Move,sparkles:Sparkles,zap:Zap,match:Check};
const STORAGE="nestpro-cms-v1";
const SLUGS={"Nest-Pro V2.0":"nest-pro","Sticker Layout":"sticker-layout","Production Tools":"production-tools"};
function Brand({c}){return <a href="/" className="brand"><span>{c.site.brand}</span><sup>{c.site.brandTag}</sup></a>}
function Nav({c}){return <header className="nav-wrap"><nav className="nav shell"><Brand c={c}/><div className="nav-links"><a href="#tools">Tools</a><a href="#about">About</a><a href="#articles">Resources</a></div><a href="#tools" className="nav-buy">Explore tools <ArrowRight size={15}/></a></nav></header>}
function ProductCard({p,index}){const slug=SLUGS[p.name]||"production-tools";return <article className={"product-card "+(index===0?"product-primary":"")}><div className="product-card-top"><span>{p.tag}</span><div className="product-icon">{index===0?<Zap size={18}/>:<Sparkles size={18}/>}</div></div><h3>{p.name}</h3><p>{p.description}</p><ul>{p.features.slice(0,4).map(x=><li key={x}><Check size={13}/>{x}</li>)}</ul><a href={"/tools/"+slug}>{index===0?"View tool details":"Explore tool"} <ArrowRight size={14}/></a></article>}
function Home(){const[c,setC]=useState(defaultContent);useEffect(()=>{try{const raw=localStorage.getItem(STORAGE);if(raw)setC(JSON.parse(raw));}catch{}},[]);const theme=useMemo(()=>({'--page-bg':c.theme.pageBg,'--surface':c.theme.surface,'--surface2':c.theme.surface2,'--text':c.theme.text,'--muted':c.theme.muted,'--line':c.theme.line,'--accent':c.theme.accent,'--accent-text':c.theme.accentText,'--dark-band':c.theme.darkBand,'--soft-band':c.theme.softBand,'--radius':c.theme.radius+"px"}),[c.theme]);return <main id="top" style={theme}><Nav c={c}/><section className="directory-hero shell"><p className="eyebrow">PRODUCTION SOFTWARE FOR ADOBE ILLUSTRATOR</p><h1>Tools for a <em>smarter</em><br/>production workflow.</h1><p className="directory-lead">Purpose-built tools for apparel production, print preparation and repetitive design tasks. Choose a tool to explore its features, tutorials, updates and licensing options.</p><a className="button dark" href="#tools">Explore all tools <ArrowRight size={16}/></a><div className="directory-stats"><span><b>01</b> Available tool</span><span><b>02+</b> Tools in development</span><span><b>AI / PDF</b> Production workflows</span></div></section><section id="tools" className="products-section shell"><div className="section-heading"><div><p className="eyebrow">TOOL DIRECTORY</p><h2>Find the right tool<br/>for the job.</h2></div><p>Every product has its own page for full feature details, downloads or licensing, tutorials, release notes and product-specific news.</p></div><div className="product-grid">{c.products.cards.map((p,i)=><ProductCard key={p.name} p={p} index={i}/>)}</div></section><section id="about" className="directory-about shell"><div><p className="eyebrow">BUILT FOR PRODUCTION</p><h2>Less repetitive work.<br/><em>More control.</em></h2></div><div><p>We build focused utilities that help design and production teams move from source files to organized, production-ready documents with fewer manual steps.</p><div className="about-points"><span><ScanLine/> Pattern and artwork workflows</span><span><Layers3/> Organized files and layers</span><span><Zap/> Purpose-built automation</span></div></div></section><section id="articles" className="resource-strip"><div className="shell resource-inner"><div><p className="eyebrow">LEARN & EXPLORE</p><h2>Guides, updates and practical tips.</h2><p>Find tutorials and product news inside each tool’s own resource center.</p></div><a className="button outline" href="/tools/nest-pro#resources">Browse Nest-Pro resources <ArrowRight size={15}/></a></div></section><footer className="footer shell"><span>{c.site.footerLeft}</span><span>Production automation for Adobe Illustrator</span><span>© 2026 Nest-Pro</span></footer></main>}
export default Home;
