"use client";
import { useParams } from "next/navigation";
import { ArrowLeft, ArrowRight, BookOpen } from "lucide-react";

const ARTICLES={
 "nest-pro":{
  "getting-started":{type:"GUIDE",title:"Getting started with Nest-Pro V2.0",intro:"A practical overview of the Nest-Pro workflow, from importing pattern files to preparing the final document.",sections:[["Start with a clean source file","Prepare your AI or PDF pattern file and confirm that the intended pattern details are visible and organized before scanning."],["Choose the right scan mode","Use Quick Scan when speed is the priority for lighter documents. Use High Performance Scan for larger or more complex files when deeper recognition is needed."],["Review the detected sizes","Check the detected sizes and layer organization before moving into placement and nesting. Confirm the output against your source pattern."],["Run nesting and inspect the result","Review piece orientation, spacing and the final arrangement. Always inspect the result before using it for production."]]},
  "scan-modes":{type:"TUTORIAL",title:"Choosing Quick Scan or High Performance Scan",intro:"Choose a scan mode based on the complexity of the Illustrator document and the time available.",sections:[["Quick Scan","Start with Quick Scan for lighter documents or when you want a faster initial pass."],["High Performance Scan","Choose High Performance Scan for more complex documents where additional recognition work may be useful."],["Verify the output","Regardless of mode, compare the detected shapes and sizes with the source file before relying on the result."]]},
  "nesting-workflow":{type:"WORKFLOW",title:"A cleaner pattern-to-nesting workflow",intro:"A repeatable sequence helps keep pattern files easier to inspect and prepare for production.",sections:[["Import and inspect","Start by confirming that the file opens correctly and the intended pattern details are present."],["Scan and organize","Run the scan and review detected sizes before moving to artwork placement."],["Nest and validate","Run nesting, inspect orientation and spacing, then save a clearly organized output file."]]}
 },
 "sticker-layout":{"sticker-layout-overview":{type:"PRODUCT UPDATE",title:"What we’re building in Sticker Layout",intro:"A first look at the planned sheet setup, object sizing and cut-margin workflow.",sections:[["Set the sheet","The planned workflow will allow users to set a target sheet size and choose measurement units."],["Define sticker dimensions","Width and height controls are planned so the layout can target a required sticker size."],["Plan spacing and cut margins","Spacing and an optional cutting safety margin are part of the planned production workflow."],["Development status","Sticker Layout is in development. Features and availability may change before release."]]}},
 "production-tools":{"production-tools-roadmap":{type:"ROADMAP",title:"Production Tools roadmap",intro:"This section will collect announcements about future production-focused utilities.",sections:[["Focused utilities","The goal is to create smaller tools for specific repetitive tasks rather than one overloaded interface."],["Product-specific resources","Each tool will have its own details, release notes and tutorials so users can find relevant information quickly."],["Follow updates","New tools and launch information will be published here as plans become ready to share."]]}}
};
export default function ArticlePage(){const params=useParams();const slug=String(params?.slug||"");const articleSlug=String(params?.articleSlug||"");const article=ARTICLES[slug]?.[articleSlug];const toolName=slug==="nest-pro"?"Nest-Pro V2.0":slug==="sticker-layout"?"Sticker Layout":"Production Tools";if(!article)return <main className="not-found shell"><a href={"/tools/"+slug}>← Back to tool</a><h1>Article not found</h1><p>This article is not available yet.</p></main>;return <main className="article-page"><header className="nav-wrap"><nav className="nav shell"><a href="/" className="brand"><span>Nest-Pro</span><sup>AI</sup></a><div className="nav-links"><a href={"/tools/"+slug+"#features"}>Features</a><a href={"/tools/"+slug+"#resources"}>Resources</a></div><a href={"/tools/"+slug} className="nav-buy">Back to tool <ArrowRight size={15}/></a></nav></header><div className="shell article-breadcrumb"><a href="/">All tools</a><span>/</span><a href={"/tools/"+slug}>{toolName}</a><span>/</span><span>Article</span></div><article className="article-body shell"><a className="article-back" href={"/tools/"+slug+"#resources"}><ArrowLeft size={14}/> Back to {toolName} resources</a><span className="status-label"><i/> {article.type}</span><h1>{article.title}</h1><p className="article-intro">{article.intro}</p><div className="article-banner"><BookOpen size={28}/><span>{toolName} <b>·</b> Resource center</span></div>{article.sections.map(([heading,body],i)=><section className="article-section" key={heading}><span>{String(i+1).padStart(2,"0")}</span><div><h2>{heading}</h2><p>{body}</p></div></section>)}<div className="article-bottom"><p>Need more information about {toolName}?</p><a className="button dark" href={"/tools/"+slug+"#resources"}>Explore more resources <ArrowRight size={15}/></a></div></article><footer className="footer shell"><a href="/">Nest-Pro</a><span>{toolName} · Resource center</span><a href={"/tools/"+slug}>Back to tool</a></footer></main>}
